### ISSUE TITLE
LoRa-E5 Development Kit

### ISSUE THREAD

**Issue by AlexFouilleul** [Seeed-Studio/fritzing_parts#10]
Hello, 

I am a French student at Polytech Grenoble working on a project to offer tutorials around your boards on this website : https://stm32python.gitlab.io/fr-version-lora/riot.html

I would like to know if you can create the Fritzing library for the following board:
- LoRa-E5 Development Kit : https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html
- LoRa-E5 Mini : https://www.seeedstudio.com/LoRa-E5-mini-STM32WLE5JC-p-4869.html 

Can you add the libraries of these boards?
Thank you in advance.

**Comment by meilily** [comment]
Hi Alex, sorry for the long silence. You got the point that we indeed need Fritzing parts for all the Wio-E5 Series also the Wio-E5-LE Series (they share the same pins, some the fritzing parts should be the same), which includes [Grove Wio-E5 Module](https://www.seeedstudio.com/Grove-LoRa-E5-STM32WLE5JC-p-4867.html), [Wio-E5 Mini Dev Board](https://www.seeedstudio.com/LoRa-E5-mini-STM32WLE5JC-p-4869.html), and [Wio-E5 Development Kit](https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html). We'll invite our contributor to work on this project, and keep you updated.

Notes for contributors, please PR [this repo here](https://github.com/Seeed-Studio/fritzing_parts) to contribute once you have the Fritzing parts ready. Here you can find more guides on how to [create Fritzing parts](https://fritzing.org/learning/tutorials/creating-custom-parts)

**Comment by meilily** [comment]
Hi @AlexFouilleul, we're super excited to share that we now have the Fritzing parts ready for Wio-E5 Mini Dev Board, and Wio-E5 Development Kit. A big shout-out to our contributor @gokuxmaker for making this possible! You can download the parts here: https://github.com/Seeed-Studio/fritzing_parts/tree/master/LoRa-E5%20Dev%20Boards
