### ISSUE TITLE
supporting Seeed Studio XIAO Series

### ISSUE THREAD

**Issue by c64emulator** [Seeed-Studio/fritzing_parts#11]
Missing all parts of the Seeed Studio XIAO Series:
- Seeed Studio XIAO ESP32S3
- Seeed Studio XIAO ESP32S3 Sense
- Seeed Studio XIAO ESP32C3
- Seeed Studio XIAO nRF52840 
- Seeed Studio XIAO nRF52840 Sense
- Seeed Studio XIAO RP2040
- Seeed Studio XIAO SAMD21

 Should be better supported.

**Comment by meilily** [comment]
Fritzing parts for [Seeed Studio XIAO nRF52840](https://forum.fritzing.org/t/seeed-studio-xiao-nrf52840/18403), created by Peter Aka [Vanepp](https://forum.fritzing.org/u/vanepp)

**Comment by meilily** [comment]
Announcing Seeed Studio XIAO Fritzing parts, now available on our GitHub repository! Special thanks to our contributor, @gokuxmaker, for the dedication and hard work in creating these parts. Download the parts here: https://github.com/Seeed-Studio/fritzing_parts/tree/master/XIAO%20Boards
