### ISSUE TITLE
grove piezo vibration sensor 

### ISSUE THREAD

**Issue by athoi92** [Seeed-Studio/fritzing_parts#4]
are there grove piezo vibration sensor's fritzing library?

**Comment by jaseiffert** [comment]
I don't have one of those but if you can get me a really nice picture from the top I could probably make you one. I've been playing with the Adafruit eagle2fritzing program and it takes eagle cad files and converts them to Fritzing files. They need to be cleaned up and fixed but better than making the whole thing from scratch. I've just found photos from the side but a top down close up would be good.
