### ISSUE TITLE
Contributing Parts

### ISSUE THREAD

**Issue by GabrielNotman** [Seeed-Studio/fritzing_parts#9]
A few years back I created a number of Fritzing parts for several SODAQ boards as well as a number of Grove parts.
The parts along with the source graphics (in SVG format) can be found here:
https://github.com/GabrielNotman/SODAQ_Fritzing

Recently someone suggest that I submit these parts as a contribution to your library.

If you are interested in adding these items please let me know how you would like to proceed.
I can make a PR, but I will need some guidance on how you want the directories organised.

**Comment by Pillar1989** [comment]
@GabrielNotman Thank you very much. We are looking forward to your PR.
